name: wire_example_shared
description: examples of shared code using git-subrepo
version: 0.0.3
# publish_to: none

environment:
  sdk: "^3.10.4"

dependencies:
  wire: ^1.6.1
  web: ^1.1.1
  hive: ^2.2.3
  lints: ^6.0.0
  path_provider: ^2.0.11
